baseurl = "https://daiwata.github.io/hugo-sample/"
title = "Hugo Sample"
languageCode = "site language code"
copyright = "Copyright right infomation."
themesdir = "themes"
theme = "ace-documentation"
Paginate=15 
MetaDataFormat = "toml"
PaginatePath="page"
pygmentsuseclasses = true
disqusShortname = "user id"
googleAnalytics='google analytics code'

hasCJKLanguage = true
preserveTaxonomyNames = false
disablePathToLower =false 
enableEmoji = true
enableInlineShortcodes = true
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"
  summaryLength = 250 # default 70
[params]
  hljsStyle="github" #code highlightjs css style . See [Style List](https://github.com/highlightjs/highlight.js/tree/master/src/styles "CSS Style list")

  showNextAndPrePost = false #Is Show Next and Previous Post Button
  description = "site description"
  keywords = "site keywords use seo"
  googleSiteVerification = "google site verification key"
  author = "your name"
  github ="github username"
  email="your email"
  twitter="your twitter name" 
  securityPolicy = false #disable https content security policy
  footerRight="Your tips content" #footer right content
  mainSections = ['page']
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
